auto: true
markdown: rdiscount
pygments: true

title: HJKing's Blog

url: http://hjking.github.io

permalink: /:year/:month/:day/:title/

author:
    name: Jin Hong
    email: hon9jin@gmail.com
    github: hjking
    twitter: hon9jin
    facebook: kin9hom
    linkedin: kinghom
    gravatar: http://www.gravatar.com/avatar/f5f95a698d284cdb1acece79504077db.png

paginate: 7

comments:
    provider: disqus
    disqus:
        short_name: hjking

analytics:
    provider: google
    google:
        tracking_id: 'UA-6627086-2'
        domain: 'hjking.github.io'

links:
    github: https://github.com/hjking
    linkedin: http://www.linkedin.com/in/kinghom
    blog: http://hjking.github.io
    blog_repo: https://github.com/hjking/hjking.github.com
    weibo: http://weibo.com/hon9jin
    twitter: https://twitter.com/hon9jin
    facebook: https://www.facebook.com/kin9hom
    gplus: https://plus.google.com/103205960311343871154/posts
    feedback: https://github.com/hjking/Feedback