auto: true
markdown: rdiscount
pygments: true

title: HJKing's Blog
description: "Personal website for HJKing, an ASIC engineer in Wuhan, China."

url: http://hjking.github.io

permalink: /:year/:month/:day/:title/

author:
    name: HJKing
    username: hjking
    email: hon9jin@gmail.com
    github: hjking
    twitter: hon9jin
    facebook: kin9hom
    linkedin: kinghom
    gravatar: http://www.gravatar.com/avatar/f5f95a698d284cdb1acece79504077db.png

paginate: 7

comments:
    provider: uyan
    disqus:
        short_name: hjking
    uyan:

analytics:
    provider: google
    google:
        tracking_id: 'UA-6627086-2'
        domain: 'hjking.github.io'
    baidu:
        site_id :


tags_path: /tags.html
category: category

links:
    github: https://github.com/hjking
    bitbucket: https://www.bitbucket.org/kinghom
    linkedin: http://www.linkedin.com/in/kinghom
    blog: http://hjking.github.io
    blog_repo: https://github.com/hjking/hjking.github.com
    weibo: http://weibo.com/hon9jin
    twitter: https://twitter.com/hon9jin
    facebook: https://www.facebook.com/kin9hom
    gplus: https://plus.google.com/103205960311343871154/posts
    feedback: https://github.com/hjking/Feedback
    bootstrap: http://getbootstrap.com
    jekyll: http://jekyllrb.com
    github_pages: https://pages.github.com
    instagram: http://instagram.com/kinghom
    lastfm: http://www.last.fm/user/KingHom
    tumblr: http://kinghom.tumblr.com
    stackoverflow: http://stackoverflow.com/users/1605724/hjking
    foursquare: https://foursquare.com/kinghom
    flickr: http://www.flickr.com/photos/kinghom
    weibo: http://weibo.com/hon9jin
    renren: http://www.renren.com/200047031/profile

# Settings for sharing
# Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
# Add a tweet button        => provider : tweet
# Add a like button         => provider : like (you also need a facebook appid)
# Add a plus one button     => provider : plusone
# Add a HN button       => provider : hn
# Add them all (i.e. hn + tweet + plusone + like) => provider : all
# Set 'provider' to the sharing provider you want to use.
# Set 'provider' to false to turn sharing off globally.
#
sharing :
    provider : all
    twitter :
        size :
        via :
        count :
    facebook :
        appid : 123
        layout : button_count
        font :
        faces : false
        width : 90
    googleplus :
        size : medium
        width :
        annotation : bubble
    linkedin :
        counter : right
