auto: true
markdown: rdiscount
pygments: true

title: HJKing's Blog

url: https://hjking.github.io

permalink: /:year/:month/:day/:title/

author:
    name: Jin Hong
    email: hon9jin@gmail.com
    github: hjking
    twitter: hon9jin
    facebook: hon9jin
    linkedin: kinghom
    gravatar: http://www.gravatar.com/avatar/f5f95a698d284cdb1acece79504077db.png

paginate: 7
    
comments:
    provider: disqus
    disqus:
        short_name: hjking

analytics:
    provider: google
    google:
        tracking_id: 'UA-18015420-1'
        domain: 'in-the-attic.com'
