markdown: kramdown
highlighter: rouge
encoding: utf-8

title: HJKing
description: "Personal website for HJKing, an ASIC engineer in Wuhan, China."

url: http://hjking.github.io

# permalink: /blog/:year/:month/:day/:title
permalink: /blog/:year/:month/:day/:title.html

author:
    name: HJKing
    username: hjking
    email: hon9jin@gmail.com
    github: hjking
    twitter: HJKIN9
    facebook: kin9hom
    linkedin: hjking
    gravatar: http://www.gravatar.com/avatar/f5f95a698d284cdb1acece79504077db.png

# paginate: 7

blog:
    cover: true

comments:
    provider: livere
    disqus:
        short_name: hjking
    uyan:

analytics:
    provider: google
    google:
        tracking_id: 'UA-6627086-2'
        domain: 'hjking.github.io'
    baidu:
        site_id :


about_path: /pages/about.html
tags_path: /pages/tags.html
categories_path: /pages/categories.html
archive_path: /pages/all_archives.html
wiki_path: /pages/wiki.html
category: category

links:
    github: https://github.com/hjking
    bitbucket: https://www.bitbucket.org/kinghom
    blog: http://hjking.github.io
    blog_repo: https://github.com/hjking/hjking.github.com
    blog_zip: https://github.com/hjking/hjking.github.com/archive/master.zip
    feedback: https://github.com/hjking/hjking.github.com/issues/new
    bootstrap: http://getbootstrap.com
    jekyll: http://jekyllrb.com
    github_pages: https://pages.github.com

# Settings for sharing
# Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
# Add a tweet button        => provider : tweet
# Add a like button         => provider : like (you also need a facebook appid)
# Add a plus one button     => provider : plusone
# Add a HN button       => provider : hn
# Add them all (i.e. hn + tweet + plusone + like) => provider : all
# Set 'provider' to the sharing provider you want to use.
# Set 'provider' to false to turn sharing off globally.
#
sharing :
    provider : jiathis
    twitter :
        size :
        via :
        count :
    facebook :
        appid : 123
        layout : button_count
        font :
        faces : false
        width : 90
    googleplus :
        size : medium
        width :
        annotation : bubble
    linkedin :
        counter : right
    jiathis:
        user_id : 1887218
    baidu:

sociallink:
  - title: LinkedIn
    href: http://www.linkedin.com/in/hjking
    class: fa fa-linkedin-square
  - title: GitHub
    href: https://github.com/hjking
    class: fa fa-github-square
  - title: Bitbucket
    href: https://www.bitbucket.org/kinghom
    class: fa fa-bitbucket-square
  - title: Stack Overflow
    href: http://stackoverflow.com/users/1605724/hjking
    class: fa fa-stack-overflow
  - title: Facebook
    href: https://www.facebook.com/kin9hom
    class: fa fa-facebook-square
  - title: Twitter
    href: https://twitter.com/hon9jin
    class: fa fa-twitter-square
  - title: Google+
    href: https://plus.google.com/103205960311343871154/posts
    class: fa fa-google-plus-square
  - title: Instagram
    href: http://instagram.com/kinghom
    class: fa fa-instagram
  - title: Flickr
    href: http://www.flickr.com/photos/kinghom
    class: fa fa-flickr
  - title: Foursquare
    href: https://foursquare.com/kinghom
    class: fa fa-foursquare
  - title: Weibo
    href: http://weibo.com/hon9jin
    class: fa fa-weibo
  - title: Renren
    href: http://www.renren.com/200047031/profile
    class: fa fa-renren
  - title: LastFM
    href: http://www.last.fm/user/KingHom
    class: fa fa-music
  - title: Tumblr
    href: http://kinghom.tumblr.com
    class: fa fa-tumblr-square
  - title: 500px
    href: http://500px.com/hjking
    class: fa fa-500px

# Custom vars
cover:      /assets/img/cover.jpg

libs:
    bootstrap:
        version: 3.3.7
        path: /assets/bootstrap
    font-awesome:
        version: 4.6.3
        path: /assets/font-awesome

plugins:
  - jekyll-paginate-v2

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

############################################################